terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at batch_permutation_op.cu:66] X.dim32(0) > 0. 0 vs 0
Error from operator: 
input: "614" input: "609" output: "input.68" name: "" type: "BatchPermutation" device_option { device_type: 1 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7fbaace25787 in /home/qiu/Projects/libtorch/libtorch-cxx11-abi-shared-with-deps-1.5.1+cu101/libtorch/lib/libc10.so)
frame #1: caffe2::BatchPermutationOp<float, caffe2::CUDAContext>::RunOnDevice() + 0x440 (0x7fba62fee670 in /home/qiu/Projects/libtorch/libtorch-cxx11-abi-shared-with-deps-1.5.1+cu101/libtorch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x35d36e2 (0x7fba62fa86e2 in /home/qiu/Projects/libtorch/libtorch-cxx11-abi-shared-with-deps-1.5.1+cu101/libtorch/lib/libtorch_cuda.so)
frame #3: caffe2::SimpleNet::Run() + 0x196 (0x7fba9e374336 in /home/qiu/Projects/libtorch/libtorch-cxx11-abi-shared-with-deps-1.5.1+cu101/libtorch/lib/libtorch_cpu.so)
frame #4: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x772 (0x7fba9e3bc372 in /home/qiu/Projects/libtorch/libtorch-cxx11-abi-shared-with-deps-1.5.1+cu101/libtorch/lib/libtorch_cpu.so)
frame #5: Mask_RCNN::run(cv::Mat&) + 0x38e (0x5586026077dc in /home/qiu/Projects/Self-Correction-Human-Parsing/mhp_parsing/deploy/build/mhp_parsing)
frame #6: main + 0x2d1 (0x55860260af32 in /home/qiu/Projects/Self-Correction-Human-Parsing/mhp_parsing/deploy/build/mhp_parsing)
frame #7: __libc_start_main + 0xe7 (0x7fba5e63fb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: _start + 0x2a (0x55860260525a in /home/qiu/Projects/Self-Correction-Human-Parsing/mhp_parsing/deploy/build/mhp_parsing)

Aborted (core dumped)